# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 记录工作...
email: ruanyu@x3platform.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daily.x3platform.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  yoshow

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal

# Baidu TongJi Baidu
baidu_tongji: 50ec37835e145af07441db70959c8575

# lunr search
# lunr_search:
#  excludes: [feed.xml]